name: Test CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        deno-version: [1.36.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Start server
        run: deno task dev
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Integration test
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.0.0/hurl_4.0.0_amd64.deb
          sudo dpkg -i hurl_4.0.0_amd64.deb
          hurl --test *.hurl
