name: Test CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        deno-version: [1.36.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start server
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.0.0/hurl_4.0.0_amd64.deb
          sudo dpkg -i hurl_4.0.0_amd64.deb
          ./test.sh http://localhost:8000
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ADMIN_PASS: ${{ secrets.ADMIN_PASS }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

