name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.36.4]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Test Deno Module
        run: deno test --unstable -A

